### ISSUE TITLE
Away from OpenCV :) - undefined symbol: cvReleaseImage

### ISSUE THREAD

**Issue by oleg-milantiev** [JiangXL/qhyccd-python#1]
Thanks for code!

Try to use your example and got
OSError: /usr/local/lib/libqhyccd.so: undefined symbol: cvReleaseImage

But ./SingleFrameMode from QHY SDK work good.

Is your binding require opencv? Is it mandatory? :(

**Comment by oleg-milantiev** [comment]
build libqhy from indi-3rdparty, error lost

**Comment by lamyc** [comment]
> build libqhy from indi-3rdparty, error lost

Can I ask for yoir help on how to do that?
I got the exact same problem as you and I am unable to compile opencv3.4 somehow.

I have installed indi-qhy now, but I have no idea how to access the indi version of qhy driver with the python scripts in this repo.

**Comment by JiangXL** [comment]
Hi! To access the indi version driver, you can use `find /usr -name libqhyccd.so` to locate `libqhyccd.so`. Then, the library path should be modified at line `self.sdk= CDLL('/usr/local/lib/libqhyccd.so')` in qhyccd.py.

Hope it  help!

**Comment by lamyc** [comment]
@JiangXL Thank you for your help! It's now working perfectly fine!

To those who have the same problem, I created a soft link to point `/usr/local/lib/libqhyccd.so` to the correct path after using the `find` command to find the correct path, so I don't have to modify the code.

**Comment by JiangXL** [comment]
Happy to know.

I guess that the old qhy driver depended on opencv cause your previous error. New qhy driver may already remove opencv dependence.

**Comment by lamyc** [comment]
bad news: the latest version of sdk still requires opencv
worse news: it requires opencv3, not 4
even worse news: it's impossible to compile opencv3, at least not for me.

It took me 2 days already trying to compile opencv3, not sure what dependency is broken.  I was following the old version official installation guide, but still.

**Comment by JiangXL** [comment]
Sorry to hear that. 

But in my case, this repo works under opencv4. 
In fact, I think that opencv only involve in demo code instead of camera driver. I'm not sure. 

If you are struggle with opencv issue, you better turn help from QHYCCD.
