### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by oleg-milantiev** [JiangXL/qhyccd-python#2]
QHYCCD|QHYCCD.CPP|InitQHYCCDResource|Load ini filePath = /root/install/qhyccd-python  fileName = qhyccd.ini
Open camera: b'QHY5-M-'
Set exposure to 100.0
Traceback (most recent call last):
  File "/root/install/qhyccd-python/./a.py", line 7, in <module>
    qc.SetExposure(qc, 1000) # set exposure to 1000ms
TypeError: qhyccd.SetExposure() takes 2 positional arguments but 3 were given

**Comment by oleg-milantiev** [comment]
maybe:

import qhyccd # import qhyccd wrapper
import numpy as np
from PIL import Image


qc = qhyccd.qhyccd() # create qhyccd object
qc.SetExposure(1000) # set exposure to 1000ms

image = Image.fromarray(qc.GetSingleFrame())
image.save('a.jpg')

**Comment by JiangXL** [comment]
Yes, you are right. I forget to update the demo.py and README.  I will update it soon.

On May 16, 2023, at 22:26, Oleg Milantiev ***@***.***> wrote:

﻿

maybe:

import qhyccd # import qhyccd wrapper
import numpy as np
from PIL import Image

qc = qhyccd.qhyccd() # create qhyccd object
qc.SetExposure(1000) # set exposure to 1000ms

image = Image.fromarray(qc.GetSingleFrame())
image.save('a.jpg')

**Comment by JiangXL** [comment]
Thanks! I have updated the example at commit d9e1914.
